### PR TITLE
Please add comments to this PR ;)

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by towanda** [comment]
It takes quordlepleen 2 - 3 minutes to update metabase.

**Comment by ifosch** [comment]
I might add more PRs... could be interesting to have some more, and some of these also merged and closed :) I'm trying to get the time to close or time to merge :)

**Comment by towanda** [comment]
@ifosch Sounds good 😄

**Comment by yaneq** [comment]
Hey, what is this sorcery?

**Comment by dsager** [comment]
:tractor: :cow2: :sheep:

**Pull request closed without merging**
