### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by towanda** [comment]
I don't this this should be integrated.

**Comment by towanda** [comment]
-1

**Comment by towanda** [comment]
+1

**Comment by nicolas-fricke** [comment]
ignore me: test comment to test my script 😛

**Comment by towanda** [comment]
@nicolas-fricke copiota 😆

**Comment by ifosch** [comment]
stupid comment

**Comment by dsager** [comment]
+1

**Pull request merged**
